//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Families
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Families()
        {
            this.VolunteerAndFamily = new HashSet<VolunteerAndFamily>();
            this.OrganizationAndFamily = new HashSet<OrganizationAndFamily>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int Id { get; set; }
        public string FirstNameFather { get; set; }
        public string FirstNameMother { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public string PelephoneFather { get; set; }
        public string PelephoneMother { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public int NumChildren { get; set; }
        public string Reference { get; set; }
        public string Reason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteerAndFamily> VolunteerAndFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationAndFamily> OrganizationAndFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
