//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int Id { get; set; }
        public int IdFamilyOrIdEvent { get; set; }
        public int IdVolunteerOrGroup { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Comments { get; set; }
        public System.DateTime dateAdded { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
