//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbRamotEntities1 : DbContext
    {
        public dbRamotEntities1()
            : base("name=dbRamotEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Families> Families { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Volunteers> Volunteers { get; set; }
    }
}
